Add a License section to readme
android/location-samples pull request #325
Opened 2023-03-24 19:50 UTC by jdkoren

Change-Id: If1dedcd39677d0bf92e9c2fed071b9d4b7bd3a6b

2023-03-24 20:15 UTC, javadude submitted a review, later dismissed

2023-03-31 17:14 UTC, tjohns submitted a review, later dismissed
LGTM

2023-03-31 19:02 UTC, tjohns approved these changes

2023-03-31 20:39 UTC, tjohns approved these changes

2023-04-03 17:49 UTC, androidbyexample approved these changes

2023-04-03 17:55 UTC, androidbyexample requested changes
blah blah

2023-04-05 17:48 UTC, closed without merging